const OLD_surgesTable = {
    "major": {
        "1": "You are the center of a massive explosion. You and each creature within 60 feet of you must make a Dexterity saving throw against your spell save DC, taking 2d10 force damage for each level of your character on a failed save, or half as much damage on a successful one.",
        "2": "You recover all your expended spell slots or class resources.",
        "3": "You are deafened for one week.",
        "4": "Each creature within 60 feet of you takes 4d10 necrotic damage. You regain hit points equal to the sum of damage dealt.",
        "5": "You are teleported to an empty demiplane for 1 day before returning to the location you left.",
        "6": "You are protected from creatures from the same plane as the one you're currently on for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC.",
        "7": "You are at the center of a darkness spell for 1 week.",
        "8": "You are frightened by the nearest creature until the end of your next turn.",
        "9": "You are resistant to all damage types for 1 minute.",
        "10": "A random creature within 60 feet of you is poisoned for 1d4 hours.",
        "11": "Make a Wisdom saving throw against your own spell save DC. If you fail, you are polymorphed into giant dragonfly for 1 minute.",
        "12": "Up to three creatures you choose within 30 feet of you take 4d10 lightning damage.",
        "13": "You immediately gain 200 temporary hit points.",
        "14": "You teleport up to 60 feet to an unoccupied space that you can see.",
        "15": "You are the center of a silence spell for 1 minute.",
        "16": "You are vulnerable to creatures from a different plane than the one you're currently on for 1 hour. Such creatures gain advantage on attack rolls made against you.",
        "17": "For the next day, any time you make an ability check, roll 1d6 and subtract the result.",
        "18": "For any spell that requires a saving throw you cast within the next minute, the target gains advantage. You have disadvantage on any attack roll you make within the next minute.",
        "19": "The next single target spell or attack you cast/make within the next minute must target one additional target.",
        "20": "A demon whose CR is equal to your level appears near you. Make a Charisma saving throw against your spell save DC. If you make it, the demon is subservient, otherwise, it is hostile. The demon, if not banished or defeated, vanishes after 1 day.",
        "21": "For the next minute, every creature within 60 feet of you that hears you speak only hears insults as if you are casting vicious mockery at first level.",
        "22": "For the next day, you have advantage on the next 2d6 rolls you make where you don't already have advantage.",
        "23": "You are protected from creatures from a different plane than the one you're currently on for 1 day. Such creatures cannot attack you or harm you unless they save a Charisma saving throw against your spell save DC.",
        "24": "For 1 minute, a duplicate of yourself appears in the nearest open space which can take actions independently, and goes on the same Initiative as you. However, any damage it takes as well as any spell slots or class resources it uses applies to you as well.",
        "25": "A loud boom emanates from you. All creatures within 15 feet take 2d8 thunder damage and must make a Constitution saving throw against your spell save DC or be deafened for 1 minute.",
        "26": "All creatures within 60 feet of you regain 2d8 hit points.",
        "27": "You permanently gain the ability to attune to one additional item.",
        "28": "You are immune to disease for 1 week.",
        "29": "You immediately drop to 0 hit points.",
        "30": "Make a Wisdom saving throw against your own spell save DC. If you fail, you are transformed into a raven for 1 minute, as if by a polymorph spell.",
        "31": "For the next minute, you are at the center of a Moonbeam (2nd lvl) that moves with you but you are immune to it's effects.",
        "32": "You and one creature you can see become vulnerable to all damage for one minute.",
        "33": "You stand at the center a circular wall of fire with a radius of 15 feet. Any creature in any of the spaces covered by this fire must make a Dexterity saving throw against your spell DC or take 5d8 fire damage. The wall of fire remains for 1 minute.",
        "34": "Choose 1 permanent or triggered effect that has happened to you or somebody else that you've received from this chart and remove it, even if it was beneficial.",
        "35": "For the next minute, at the end of each of your turns, 3 magic missiles appear and target the three closest creatures to you.",
        "36": "You permanently lose the ability to smell. This sense can be restored with a spell that removes curses such as remove curse.",
        "37": "You gain the effects of the Sanctuary spell.",
        "38": "Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a cat for 1 minute, as if by a polymorph spell.",
        "39": "You gain the effects of the Enlarge spell for one day.",
        "40": "You gain the service of an arcane eye for 1 hour that does not require concentration.",
        "41": "You gain the effects of the Reduce spell for one day.",
        "42": "You transform into a medium-sized potted plant for 1 minute, during which time you are considered petrified.",
        "43": "3d6 random gems appear near you, worth 50gp each.",
        "44": "You and all allies within 20 feet of you gain a +2 bonus to attack and damage rolls on any melee weapon attack they make within the next minute.",
        "45": "For 2d6 days, you glow bright yellow. You have disadvantage on Stealth checks and anyone trying to perceive you has advantage on their Perception check.",
        "46": "You stand at the center a circular wall of force with a radius of 15 feet. Any creature in any of the spaces covered by this wall must make a Dexterity saving throw against your spell DC or take 5d8 force damage. The wall remains for 1 minute.",
        "47": "All creatures within 20 feet of you are knocked prone.",
        "48": "You gain the effects of the Nathair's Mischief spell, centered on you, for 1 min.",
        "49": "The effects of the Spike Growth spell appear centered on you for 1min.",
        "50": "You and all allies within 20 feet of you gain a +2 bonus to attack and damage rolls on any ranged weapon attack they make within the next minute.",
        "51": "You are at the center of a 10-foot radius antimagic field that negates all magic equal to or less than your level for 1 hour and does not require concentration.",
        "52": "Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a wolf for 1 minute, as if by a polymorph spell.",
        "53": "You immediately cast Warding Bond on one random ally you can see within 30ft. This effect does not end if you are separated from your ally. You cannot dismiss the spell.",
        "54": "All of your hair permanently falls out. Only a spell such as remove curse can end this effect.",
        "55": "You gain the ability to speak one new language of your choice. However, you lose the ability to speak one language you already know.",
        "56": "A 30-foot cube hypnotic pattern appears with you at the center. All creatures within the pattern must succeed on a Wisdom saving throw or fall asleep for 1 minute or until they take damage.",
        "57": "You permanently forget one cantrip. A spell such as remove curse can restore your memory.",
        "58": "You immediately take 2d10 psychic damage.",
        "59": "Until the next long rest, all traders you talk to are confused about currencies. The asking price of any item is randomly changed to any currency (i.e. a 10g item could be worth either 10g, 10s or 10c). ",
        "60": "You gain temporary hit points equal to the maximum hit points of a creature you can see. These temporary hit points last until the next long rest.",
        "61": "If you already have spell slots, you gain an additional spell slot of your highest level for 1 week. If you already have multiple attacks, you gain an additional attack for 1 week.",
        "62": "If you die within the next minute, you come back to life as if by the reincarnate spell.",
        "63": "If you already have spell slots, you permanently gain one spell slot of one level below your highest-level spell slot, but lose one 1st-level spell slot. If you don't already have spell slots, you permanently gain a first level spell slot and learn one first level spell (up to the DM). A spell such as remove curse can end this effect.",
        "64": "All creatures that can perceive you must make a Wisdom saving throw against your spell save DC or be frightened of you.",
        "65": "The spell Feign Death is cast on you.",
        "66": "The spell Time Stop is cast on you.",
        "67": "You gain the service of an arcane sword that does not require concentration until your next short or long rest.",
        "68": "You permanently gain one cantrip (up to the DM). A spell such as remove curse can end this effect.",
        "69": "All allies within 20 feet of you get gain a -2 penalty on attack and damage rolls for any melee attack they make in the next minute.",
        "70": "All allies within 20 feet of you heal up to 3d8 hit points.",
        "71": "You lose the ability to see for 1 day. During this time, you have the blinded condition.",
        "72": "You gain the service of a phantom steed for 1 week.",
        "73": "Make a Constitution saving throw against your spell save DC. If you fail, you are stunned for 1 minute.",
        "74": "Your max hp permanently increases by 20",
        "75": "All creatures within 20 feet of you, including you, must make a Dexterity save against your spell save DC or be affected by a faerie fire spell.",
        "76": "Permanently increase one ability score of your choice by 1 point. Permanently decrease a different ability score of your choice by 1 point. A spell such as remove curse can end this effect.",
        "77": "You permanently gain proficiency in one tool or weapon type you don't already have. A spell such as remove curse can end this effect.",
        "78": "Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a giant spider for 1 minute, as if by the polymorph spell.",
        "79": "Gain the sympathy effects of the antipathy/sympathy spell for 3d6 days.",
        "80": "For 1 min, melee attacks or spells with a range of touch have a range of 90ft instead.",
        "81": "All allies within 20 feet of you gain a -2 penalty to attack and damage rolls for any ranged attack they make within the next minute.",
        "82": "For one minute, any spell with a casting time of 1 action can be cast as a bonus action and any attack action can be taken as a bonus action.",
        "83": "Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a giant rabbit for 1 minute, as if by the polymorph",
        "84": "The next time you trigger a wild magic surge, you don't.",
        "85": "For the next day, you gain proficiency in all skills that you are not already proficient in.",
        "86": "The next time you trigger a wild magic surge, roll twice on this chart. Both effects will apply.",
        "87": "For 1 min, ranged attacks or spells with a range of more than touch, have a range of melee or touch instead.",
        "88": "Until your next long rest you are healed by poison and harmed by healing potions.",
        "89": "Gain the antipathy effects of the antipathy/sympathy spell for 3d6 days.",
        "90": "All creatures within 30 feet of you must make a Wisdom saving throw. Any creature immune to magical sleep automatically succeeds on its saving throw. Those that fail fall asleep for 1d6 minutes.",
        "91": "For 1 min, any creature you hit or affect with a spell/ability is pulled 10ft towards you.",
        "92": "All your allies within 20 feet of you gain a +2 bonus to their AC for 1 minute.",
        "93": "The next time you fall below 0 hit points within the next week, you automatically fail your first death saving throw.",
        "94": "If you already have spell slots, you gain two spell slots at your second-highest level for 1 week. If you don't already have spell slots, you gain the ability to cast one first level spell (up to the DM) per day.",
        "95": "For the next day, any time you make an ability check, roll 1d6 and add the result.",
        "96": "Make a Wisdom saving throw against your spell save DC. If you fail, you are transformed into a sheep for 1 minute, as if by the polymorph spell.",
        "97": "All allies within 30 feet of you gain a -2 penalty to their AC for 1 minute.",
        "98": "For 1 min, any creature you hit or affect with a spell/ability is pushed 10ft away from you.",
        "99": "You jump forward in time exactly 1 minute, for 1 minute. From the perspective of everyone else, you cease to exist during that time.",
        "100": "Until the start of your next turn, bodies are swapped. Every NPC is controlled by the players and every PC is controlled by the DM. After the effect ends, the characters themselves don't understand what happened."
    },
    "moderate": {
        "1": "For the next day, your skin tone changes color every 30 minutes, cycling through the colors of the rainbow.",
        "2": "You are confused for 1 minute, as though you were affected by the confusion spell.",
        "3": "Your Strength is increased by 2 for 1 day.",
        "4": "A third eye appears in your forehead, giving you advantage on sight-based Wisdom (Perception) checks for 1 minute.",
        "5": "The next attack or spell you cast within the next minute that does damage, the damage is maximized.",
        "6": "For the next minute, you can teleport up to 20 feet as part of your movement on each of your turns.",
        "7": "You become intoxicated for 2d6 hours.",
        "8": "Your Intelligence is decreased by 2 for 1 day.",
        "9": "Your Wisdom is increased by 2 for 1 day.",
        "10": "For 1 minute, any flammable item you touch, that you aren't already wearing or carrying, bursts into flame.",
        "11": "Plants grow around you and you are restrained for 1 minute.",
        "12": "A random creature within 30 feet of you gains a flying speed equal to its walking speed for 1 minute.",
        "13": "You may immediately take 1 additional action.",
        "14": "If you fall within the next day, you automatically have the benefit of the feather fall spell.",
        "15": "You recover 1 expended spell slot or one class specific resource of your choice.",
        "16": "For the next attack or spell you cast within 1 minute that does damage, the damage is minimized.",
        "17": "You have are surrounded by a spectral shield for 1 minute, giving you a +2 bonus to your AC and immunity to magic missile.",
        "18": "You and all creatures within 30 feet of you gain vulnerability to piercing damage for 1 minute.",
        "19": "For 1 minute, you gain resistance to nonmagical bludgeoning, piercing, and slashing damage.",
        "20": "You gain the effects of the Beacon of Hope spell. This effect does not require concentration.",
        "21": "For the next minute, one creature of your choice gets a -2 penalty to its AC, attack rolls, and damage rolls.",
        "22": "You and all creatures within 30 feet of you gain vulnerability to bludgeoning damage for 1 minute.",
        "23": "You emanate light in a 30-foot radius for 1 minute. Any creature within 5 feet of you that can see is blinded until the end of its next.",
        "24": "For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing black, but disadvantage if they are wearing white. If they are wearing both, this doesn't apply.",
        "25": "For the next minute, your jump distance is tripled. You can only move via jumping and you cannot choose to jump less than the maximum distance you're able to.",
        "26": "Your Intelligence is increased by 2 for 1 day.",
        "27": "Within the next hour, you have advantage on the next roll you make where you don't already have advantage.",
        "28": "You gain a +2 bonus to your AC for 1 minute.",
        "29": "Until the start of your next turn, you cast Silvery Barbs at every possible opportunity without expending any spell slots. Silvery Barbs cast this way does not empower anyone.",
        "30": "For the next minute, you gain resistance to thunder and force damage.",
        "31": "An imp appears within 30 feet of you. Make a Charisma saving throw against your spell save DC. If you succeed it, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 day.",
        "32": "For the next minute, you gain resistance to fire and cold damage.",
        "33": "For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing red, but disadvantage if they are wearing green. If they are wearing both, this doesn't apply.",
        "34": "You gain the service of an arcane eye for 1 minute that does not require concentration.",
        "35": "You lose the ability to smell for 1 day.",
        "36": "You gain a -2 penalty to your AC for 1 minute.",
        "37": "You and all creatures within 30 feet of you gain vulnerability to necrotic damage for 1 minute.",
        "38": "You become invisible and silent for 1 minute.",
        "39": "Your Dexterity is increased by 2 for 1 day.",
        "40": "You can detect the thoughts of 1 creature you can see within 30 feet of you for 1 minute.",
        "41": "For the next minute, all melee attacks you make with a non-magical weapon gain a +1 bonus to hit and to damage, and are considered magical for the purpose of overcoming resistances.",
        "42": "Your Strength is decreased by 2 for 1 hour.",
        "43": "You gain freedom of movement for 1 day.",
        "44": "Your Dexterity is decreased by 2 for 1 hour.",
        "45": "You are affected by a faerie fire spell for 1 minute. You automatically fail the saving throw.",
        "46": "For the next hour, you can speak with animals. But any creature that is not an animal does not understand what you're saying.",
        "47": "3d6 gold pieces appear near you.",
        "48": "For 2d6 hours, you have a faint pink glow. Anyone trying to perceive you has advantage on their Perception check.",
        "49": "You gain the ability to breath water for 1 day.",
        "50": "You and all creatures within 30 feet of you gain vulnerability to slashing damage for 1 minute.",
        "51": "For the next minute, light and darkness quickly alternate around you in a 30-foot radius, creating a strobe effect. Sight-based creatures gain a -1 penalty on attack rolls against you and Perception checks against you, and you gain a -10 penalty to Stealth checks.",
        "52": "All creatures within 20 feet of you must make a Strength saving throw against your spell save DC or be knocked prone.",
        "53": "For the next 24, everything you say will also be written in the sky as per the Skywrite spell.",
        "54": "For the next minute, you can pass through any solid, non-magical wall that is 6 or fewer inches thick.",
        "55": "For the next hour, you can speak with plants. But any creature that is not a plant does not understand what you're saying.",
        "56": "If you already know at least one cantrip, you permanently gain one 1st-level spell slot but forget one cantrip that you already know. If you don't already know at least one cantrip, you permanently gain the ability to cast one cantrip (up to the DM) but you loose proficiency in one skill you're proficient in. A spell such as remove curse can end this effect.",
        "57": "You immediately gain 15 temporary hit points.",
        "58": "All gold you are carrying is now silver.",
        "59": "For the next minute, you gain resistance to necrotic and radiant damage.",
        "60": "You are at the center of a fog cloud spell which lasts for 1 minute.",
        "61": "Your Charisma is increased by 2 for 1 day.",
        "62": "You and all creatures within 30 feet of you gain vulnerability to lightning damage for 1 minute.",
        "63": "You and all creatures within 30 feet of you gain vulnerability to force damage for 1 minute.",
        "64": "For the next minute, any creature you touch takes 2d6 lightning damage.",
        "65": "You gain blindsight with a radius of 60 feet for 1 minute.",
        "66": "You are surrounded by a horrible, noxious odor for 1 minute. Anyone within 10 feet of you must make a Constitution saving throw or be stunned.",
        "67": "Your Charisma is decreased by 2 for 1 hour.",
        "68": "You gain the service of a phantom steed for 1 day.",
        "69": "You and all creatures within 30 feet of you gain vulnerability to acid damage for 1 minute.",
        "70": "Your Wisdom is decreased by 2 for 1 hour.",
        "71": "Your speed is increased by 10 feet for 1 day.",
        "72": "You gain the ability to walk on water for 1 day.",
        "73": "You and all creatures within 30 feet of you gain vulnerability to psychic damage for 1 minute.",
        "74": "One creature of your choice gets a +2 bonus to all attack rolls, damage rolls, and their armor class AC for 1 minute.",
        "75": "You lose proficiency in one randomly chosen skill, tool, or weapon type for 2d6 days.",
        "76": "All food and drink within 30 feet of you becomes putrid, spoiled, or rotten. Consuming this food deals 2d6 poison damage and causes the poisoned condition for 1 hour.",
        "77": "All silver you are carrying is now copper.",
        "78": "You and all creatures within 30 feet of you gain vulnerability to fire damage for 1 minute.",
        "79": "You lose proficiency in all skill rolls for 1d4 hours.",
        "80": "The next time you roll a 1 or 20 on a d20, it will turn into the opposite.",
        "81": "For the next hour, any time you make an ability check, roll 1d6 and subtract the result.",
        "82": "For the next minute, you gain resistance to poison and psychic damage.",
        "83": "You're feeling lucky. For the next hour, any time you make an ability check, roll 1d6 and add the result.",
        "84": "You immediately take 2d6 psychic damage.",
        "85": "You gain proficiency in one skill of your choice that you're not already proficient in for one hour.",
        "86": "Your Constitution is increased by 2 for 1 day.",
        "87": "You and all creatures within 30 feet of you gain vulnerability to thunder damage for 1 minute.",
        "88": "You and all creatures within 30 feet of you gain vulnerability to cold damage for 1 minute.",
        "89": "You gain the ability to speak one language of your choice for 1 day.",
        "90": "You and all creatures within 30 feet of you gain vulnerability to radiant damage for 1 minute.",
        "91": "The next time you walk through a door or gate it will slam shut behind you and refuse to let anyone except you through. This effect persists for 24 hours.",
        "92": "For the next minute, you are unable to cast any spell that causes damage of any type.",
        "93": "You gain spider climb for 1 minute, and it does not require concentration to maintain.",
        "94": "You immediately lose all unspent class resources and may not regain them until you have finished a long rest.",
        "95": "You and all creatures within 30 feet of you gain vulnerability to poison damage for 1 minute.",
        "96": "You gain the ability to speak with animals for 1 day.",
        "97": "All food and drink within 30 feet of you is purified.",
        "98": "The next time you try to walk through a door or gate, it will slam shut and refuse to let you (and only you) through. This effect persists for 24 hours.",
        "99": "All your clothing and equipment teleports to the nearest open space at least 15 feet from you that you can see.",
        "100": "Your Constitution is decreased by 2 for 1 hour."
    },
    "minor": {
        "1": "A puddle of grease appears where you are standing, with a 10-foot radius. You and anyone within 10 feet of you must make a Dexterity check at your spell save DC or fall prone.",
        "2": "You levitate 6 inches off the ground for 1 minute.",
        "3": "You gain tremorsense with a range of 30 feet for 1 minute.",
        "4": "You make no sounds for 1 minute and you gain advantage on any Dexterity (Stealth) checks.",
        "5": "You grow a beard made of feathers, which remains until you sneeze.",
        "6": "You can't speak for 1 minute. When you try, pink bubbles float out of your mouth.",
        "7": "You are immune to intoxication for the next 5d6 days.",
        "8": "You recover your lowest-level expended spell slot. If you don't have spell slots, you recover one expended class resource instead.",
        "9": "For the next minute, you must shout when you speak.",
        "10": "Illusory butterflies and flower petals flutter in the air around you in a 10-foot radius for 1 minute.",
        "11": "You cast mirror image on yourself, which lasts for 1 minute and does not require concentration.",
        "12": "You are surrounded by faint, ethereal music for 1 minute.",
        "13": "For the next 24 hours, you perceive light as darkness and darkness as light.",
        "14": "Your hair grows to double its current length over the next minute.",
        "15": "Your hair falls out but grows back within 1 day.",
        "16": "You gain the ability to speak one additional language of your choice for 1 hour.",
        "17": "You are invisible for 1 minute.",
        "18": "Your eyes permanently change color. If they are a blue or grey shade, they turn dark brown, or vice versa. A spell such as remove curse can end this effect.",
        "19": "Small birds flutter and chirp in your vicinity for 1 minute, during which time you automatically fail any Stealth check.",
        "20": "You feel the incredible urge to relieve yourself. Until you do, your Strength and Intelligence are reduced by 1. If you don't relieve yourself in the next 2 minutes, the above effects are removed, but your Charisma score is reduced by 4 for 1 hour or until you change your trousers.",
        "21": "Gnats buzz around your head for 1 minute, distracting you. You must make a Constitution saving throw against your own spell save DC to be able to form a coherent sentence.",
        "22": "You are surrounded by a faint, offensive odor for 1 minute. You gain disadvantage on all Charisma checks.",
        "23": "For the next minute, all spells with a casting time of 1 action or 1 bonus action require 2 consecutive actions to cast.",
        "24": "You have the irresistible urge to scratch an itch in the middle your back, just out of reach, for 1 minute. If you don't scratch it using a back scratcher or some similar device , you must succeed a Constitution saving throw against your spell save DC to resist the urge of running to the nearest rough surface and rubbing your back against it.",
        "25": "You have a momentary vision of your own death. If you fail a Wisdom saving roll at your spell DC, you are frightened for 1 minute.",
        "26": "Your Charisma is increased by 2 for 1 minute.",
        "27": "For the next day, while you're speaking you gain the effect of the Light spell.",
        "28": "Your eyes glow red for 1 minute.",
        "29": "Your Constitution is increased by 2 for 1 minute.",
        "30": "You add your proficiency bonus to all Charisma checks for the next hour, if you don't already add it.",
        "31": "For the week, all alcoholic beverages in a 30ft radius around you are transformed into lukewarm water when drunk.",
        "32": "For the next minute, you have advantage on the next roll you make where you don't already have advantage.",
        "33": "Every creature within 15 feet of you takes 1 necrotic damage. If you are wounded, you regain hit points up to the amount of damage dealt. If you are not wounded, you gain this amount of temporary hit points.",
        "34": "A magic mouth appears on a nearby wall or flat surface. When you speak, your voice comes from the magic mouth. This lasts for 1 minute.",
        "35": "You can hear exceptionally well for 1 minute, gaining advantage for all Perception checks related to sound.",
        "36": "You lose the ability to smell for 1 hour.",
        "37": "For the next day, each time you say a word with the \"s\" sound, it sounds like a hissing snake.",
        "38": "A gentle gust of wind blows outward from you. All creatures within 40 feet of you can feel it, but it otherwise does nothing.",
        "39": "Your Dexterity is increased by 2 for 1 minute.",
        "40": "Some god has taken issue with the last thing you said or did. You immediately take 1d10 radiant damage.",
        "41": "One randomly-chosen non-magical item in your possession that weighs 1 pound or less vanishes and is forever gone.",
        "42": "Your Wisdom is increased by 2 for 1 minute.",
        "43": "You immediately gain 10 temporary hit points.",
        "44": "3d6 silver pieces appear near you.",
        "45": "You regain 5 hit points per round for 1 minute.",
        "46": "For the next week, any food in a 30ft radius around you becomes incredibly spicy when eaten.",
        "47": "Your speed is increased by 10 feet for 1 minute.",
        "48": "You gain proficiency on all Strength checks for the next hour, if you don't already have it.",
        "49": "Your Intelligence is increased by 2 for 1 minute.",
        "50": "One randomly-chosen non-magical item in your possession that weighs 1 pound or less is duplicated.",
        "51": "Mushrooms sprout around you in a 5-foot radius and vanish after 1 minute. If one is harvested and eaten within this time, the creature must make a Constitution saving throw against your spell save DC. On a failed save, it takes 5d6 poison damage. On successful one, it gains 5d6 temporary hit points.",
        "52": "You can smell exceptionally well for 1 minute, gaining blindsight with a radius of 10 feet and advantage on all Perception checks related to odor.",
        "53": "Your feet sink into the ground, making you completely immobile for one minute. This has no effect if you were not standing on the ground when the spell was cast.",
        "54": "One random gem worth 100gp appears near you.",
        "55": "For the next minute, you have double vision. This gives you disadvantage on ranged attacks (including spell attacks) and Perception checks involving sight.",
        "56": "You are surrounded by a faint, pleasant odor. You gain advantage on all Charisma checks you make within the next minute.",
        "57": "You lose proficiency on all skill checks for 1 minute.",
        "58": "You gain freedom of movement for 1 minute.",
        "59": "You gain darkvision with a radius of 60 feet for 1 minute. If you already have darkvision, you lose it for 1 minute.",
        "60": "Approximately 100 gallons of water appear over your head and those within 10 feet of you, evenly distributed above everybody within the radius.",
        "61": "You gain a +1 to your AC for one minute.",
        "62": "You fall victim to a horrible cramp in both legs, reducing your speed by 10 feet for 1 hour.",
        "63": "You permanently gain the ability to speak with nonexistent things.",
        "64": "For the next hour, you are unable to read as the letters all appeared jumbled.",
        "65": "For the next day, everything you say must rhyme. If it doesn't, you take 1d4 psychic damage.",
        "66": "During the next hour, you may re-roll any one save, attack roll, or skill check. If you do, you must take the new roll's result.",
        "67": "You grow 1d6 inches in height. You gradually return to your original height over the course of 1 day.",
        "68": "For the next day, every time you're even just mildly annoyed by the actions of any of your party members, you take 1d4 psychic damage and they take three times as much.",
        "69": "For the next hour, any time you make an ability check, roll 1d4 and subtract the result.",
        "70": "You gain the ability to speak with animals for one hour.",
        "71": "You get gain a -1 penalty to your AC for 1 minute.",
        "72": "You gain the use of an unseen servant for 1 hour.",
        "73": "The next beast you come across within the next 24h will take a liking to you. It will refuse to attack you unless attacked first and can be persuaded to become your pet (Persuasion or Animal Handling check to do so depends on creature's CR).",
        "74": "A bad joke comes to mind and until you tell it (which takes an entire action), you suffer a Wisdom penalty of 1.",
        "75": "You hear a ringing in your ears. The next spell you cast that requires a verbal component requires a Constitution check against your spell save DC.",
        "76": "You lose 1d6x5 pounds. You gradually return to your original weight over the course of 1 day.",
        "77": "Your clothes become dirty and filthy. Until you can change and/or clean your clothes, your Charisma is reduced by 1.",
        "78": "You gain proficiency in Wisdom checks for the next hour, if you don't already have it.",
        "79": "You shrink 1d6 inches in height. You gradually return to your original height over the course of 1 day.",
        "80": "Your skin permanently darkens as if you have a tan, or if you are already dark-skinned, your skin becomes one shade lighter. A spell such as remove curse can end this effect.",
        "81": "For 1 minute, one creature of your choice within 30 feet of you gains a -1 penalty to attack rolls, damage rolls, and their AC.",
        "82": "For the next hour, any time you make an ability check, roll 1d4 and add the result.",
        "83": "If you cast a spell or take an action with a saving throw within the next minute, the target gains disadvantage on its saving throw.",
        "84": "Your Strength is increased by 2 for 1 minute.",
        "85": "One creature of your choice gains a +1 bonus to attack rolls, damage rolls, and its AC for 1 minute.",
        "86": "You immediately heal 2d10 hit points.",
        "87": "You gain proficiency on all Intelligence checks for the next hour, if you don't already have it.",
        "88": "For the next hour, you loose the ability to speak. You have to perform an interpretive dance to end this effect. As long as you can't speak, the casting of spells requires only dancing as component.",
        "89": "You gain 1d6x10 pounds. You gradually return to your original weight over the course of 1 day.",
        "90": "You gain proficiency in all Dexterity checks for the next hour, if you don't already have it.",
        "91": "Your fingernails and toenails grow to an uncomfortable length. Until you trim them, your Dexterity is reduced by 1 and your speed is reduced by 5 feet, even if you're not wearing shoes.",
        "92": "You gain the effects of the blur spell for 1 minute, which does not require concentration to maintain.",
        "93": "For the next hour, you appear to others to be the opposite gender.",
        "94": "You gain the service of a 2nd-level spiritual weapon for 1 minute.",
        "95": "For the next hour, all traders you talk to are confused about currencies. The asking price of any item is randomly changed to another currency (i.e. a 10g item would be worth either 10s or 10c). ",
        "96": "You gain proficiency in all Constitution checks for the next hour, if you don't already have it.",
        "97": "Every inanimate object that isn't being worn or carried within 40 feet of you becomes enshrouded with shadows for 1 minute. Enshrouded objects are considered heavily obscured.",
        "98": "You realise that the next time you see an animal, you won't be able to resist the urge to try and pet it.",
        "99": "You feel extremely nauseated. Make a Constitution saving throw against your spell save DC. If you fail, you must spend your next action throwing up.",
        "100": "You realise that the next time you're up on a high platform, you won't be able to resist the urge to jump down."
    }
};

export const surgesTable = {
    major: {
        1: "You are the center of a massive explosion. You and each creature within 60 feet of you must make a Dexterity saving throw against your spell save DC, taking 2d12 force damage for each level of your character on a failed save, or half as much damage on a successful one.",
        2: "You recover all expended class resources.",
        3: "You are deafened for 1 week.",
        4: "You are silenced for 1 week.",
        5: "You are poisoned for 1 week.",
        6: "You are invisible for 1 week.",
        7: "Each creature within 60 feet of you takes 2d8 necrotic damage. You regain hit points equal to the sum of damage dealt.",
        8: "You are teleported to an empty demiplane for 1 day before returning to the location you left.",
        9: "You are protected from creatures from the same plane as the one you're currently on for 1 day. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC and will focus on other targets if they can.",
        10: "You are at the center of a darkness spell for 1 week.",
        11: "You are frightened by the nearest creature for 1 hour.",
        12: "You are resistant to all damage types for 1 hour.",
        13: "All other creatures within 60 feet of you become poisoned for 1 hour.",
        14: "All other creatures within 60 feet of you become blinded for 1 hour.",
        15: "All other creatures within 60 feet of you become deafened for 1 hour.",
        16: "All other creatures within 60 feet of you become invisible for 1 hour.",
        17: "All other creatures within 60 feet of you become restrained for 1 hour.",
        18: "You immediately gain 3d100 temporary hit points.",
        19: "You immediately lose any temporary hit points you have and drop to 1 hp.",
        20: "All attack rolls against you are made with advantage for 1 week.",
        21: "All attack rolls against you are made with disadvantage for 1 week.",
        22: "For 1 hour, other creatures have advantage on saving throws against spells you cast.",
        23: "For 1 hour, other creatures have disadvantage on saving throws against spells you cast.",
        24: "A demon whose CR is equal to your level appears near you. Make a Charisma saving throw against your own spell save DC. If you make it, the demon is subservient, otherwise, it is hostile. The demon, if not banished or defeated, vanishes after 1 day.",
        25: "All other creatures within 60ft regain 2d8 hit points each. Then you take necrotic damage for the sum of all hit points restored this way.",
        26: "You can attune to one additional item. This effect is permanent.",
        27: "You can attune to one fewer item. This effect is permanent.",
        28: "You immediately drop to 0 hit points and become immune to all damage for 2 rounds.",
        29: "Your size is permanently reduced by 1 category. This effect can only be removed by the Wish spell or by casting Greater Restoration or Remove Curse at 10th level or higher.",
        30: "Your size is permanently increased by 1 category. This effect can only be removed by the Wish spell or by casting Greater Restoration or Remove Curse at 10th level or higher.",
        31: "You transform into a medium-sized potted plant for 1 hour, during which time you are considered petrified.",
        32: "1d20 random gems appear near you, worth 5000gp each.",
        33: "All creatures within 60ft are knocked prone.",
        34: "Whenever you make an ability check using Strength, subtract 1d8 from the result. This effect is permanent.",
        35: "Whenever you make an ability check using Dexterity, subtract 1d8 from the result. This effect is permanent.",
        36: "Whenever you make an ability check using Constitution, subtract 1d8 from the result. This effect is permanent.",
        37: "Whenever you make an ability check using Intelligence, subtract 1d8 from the result. This effect is permanent.",
        38: "Whenever you make an ability check using Wisdom, subtract 1d8 from the result. This effect is permanent.",
        39: "Whenever you make an ability check using Charisma, subtract 1d8 from the result. This effect is permanent.",
        40: "Whenever you make an ability check using Strength, add 1d8 to the result. This effect is permanent.",
        41: "Whenever you make an ability check using Dexterity, add 1d8 to the result. This effect is permanent.",
        42: "Whenever you make an ability check using Constitution, add 1d8 to the result. This effect is permanent.",
        43: "Whenever you make an ability check using Intelligence, add 1d8 to the result. This effect is permanent.",
        44: "Whenever you make an ability check using Wisdom, add 1d8 to the result. This effect is permanent.",
        45: "Whenever you make an ability check using Charisma, add 1d8 to the result. This effect is permanent.",
        46: "For 1 week, no creature within 60ft of you can cast spells of 6th level or lower.",
        47: "You gain the ability to speak one new language of your choice. However, you lose the ability to speak one language you already know.",
        48: "You forget one cantrip of your choice.",
        49: "You learn one cantrip of your choice.",
        50: "You gain an additional spell slot of your highest level. If you do not have spell slots, you instead learn a 3rd level spell of your choice and gain the ability to cast it once per day.",
        51: "During this turn, you can take move and take actions equivalent to taking 5 turns.",
        52: "Your maximum hit points are permanently increased by 2d20.",
        53: "Your lowest ability score is permanently increased by 4.",
        54: "Your highest ability score is permanently reduced by 4.",
        55: "You permanently gain proficiency with one weapon or armour of your choice.",
        56: "You permanently gain proficiency with one tool of your choice.",
        57: "For 1 hour, you can cast any spell with a casting time of 1 action as a bonus action and you can take the attack as a bonus action.",
        58: "You immediately cause 4d4 additional wild magic surges.",
        59: "For 1 day min, ranged attacks or spells with a range of more than touch, have a range of melee or touch instead.",
        60: "All creatures within 60 feet must make a Wisdom saving throw against your spell save DC. Any creature immune to magical sleep automatically succeeds on its saving throw. Those that fail fall asleep for 1 hour.",
        61: "For 1 hour, every time you hit a creature with an attack, it is pulled 10ft towards you.",
        62: "For 1 hour, every time you hit a creature with an attack, it is pushed 10ft away from you.",
        63: "You jump forward in time exactly 1 minute. From the perspective of everyone else, you simply cease to exist during that time.",
        64: "For 1 hour, each player looses control over their character and instead gains control over the character who's session inspiration they can see. After the effect ends, the characters themselves don't understand what happened.",
        65: "Your walking speed is permanently increased by 30ft.",
        66: "Your walking speed is permanently decreased by 30ft.",
        67: "Whenever a creature talks to you for the first time during the effect's duration, you flip a coin. If it lands on heads, you punch them in the face, otherwise you hug them. You are not aware of this effect being anything other than you openly expressing your feelings. The effect lasts for 1 week.",
        68: "You spot a (1d6: 1=Cat, 2=Pig, 3=Frog, 4=Goat, 5=Chicken, 6=Dog) of CR 0 and firmly believe it to be a reincarnated deity, an embodiment of nature itself, or something similar according to your beliefs. You decide that you need to protect it at all costs and do everything in your power to make sure it is treated with the respect you think it deserves.",
        69: "For 1 day, your vocabulary is limited to the words \"Yes\" and \"No\", which you can only scream. During this time you cannot cast spells with verbal components.",
        70: "While asleep, you snore so loudly that no other creature within 1 mile can sleep.",
        71: "You and everything you're wearing and carrying are instantly, and without warning, transported to the elemental plane of (1d4: 1= fire, 2=water, 3=earth, 4=air). Your companions know exactly where you are.",
        72: "For 1 day, you cannot willingly move further than away 30ft from your current location. If you are moved outside this range, you must take any and all actions you can to get back as quickly as possible. Behaving like this seems perfectly reasonable to you.",
        73: "For 1 week, you can only move via jumping, and you cannot choose to jump less than the maximum distance you're able to jump.",
        74: "For 1 day, you can speak with animals but trying to speak any language will result in you making random animal noises.",
        75: "You take 1 damage for every 10gp worth of currency you're carrying.",
        76: "You gain the ability to breathe water but loose the ability to breathe air for 1 day.",
        77: "For 1 day, everything you say will also be written in the sky as per the Skywrite spell.",
        78: "For 1 day, you can pass through any solid, non-magical wall that is 6 or fewer inches thick.",
        79: "All copper and silver pieces you carry turn into platinum pieces. All other currencies you carry turn to copper pieces.",
        80: "Whenever you take a long rest, a corpse of a recently murdered humanoid creature appears in your bed.",
        81: "Every time you walk through a door or gate it will slam shut behind you and refuse to let anyone except you through.",
        82: "For 1 hour, you are unable to cast any spell that causes damage of any type.",
        83: "All your clothing and equipment teleports to the nearest unoccupied space at least 120 feet from you that you can see.",
        84: "You can only speak while music is playing.",
        85: "You are surrounded by faint, ethereal music.",
        86: "Your skin permanently changes color. (1d8: 1=Red, 2=Green, 3=Blue, 4= Purple, 5= Yellow, 6=Grey, 7=White, 8=Black)",
        87: "For 1 day, all spells  with a casting time of 1 action or 1 bonus action require 2 consecutive actions to cast.",
        88: "For 1 day, while you're speaking you gain the effect of the Light spell.",
        89: "All beverages within 120ft of you transform into lukewarm water when drunk.",
        90: "Some god has taken issue with the last thing you said or did. You immediately take 10d12 radiant damage.",
        91: "Approximately 10000 gallons of water appear over your head and those within 1000 feet of you, evenly distributed above everybody within the radius.",
        92: "You are unable to read as the letters all appeared jumbled.",
        93: "For the next day, everything you say must rhyme. If it doesn't, you take 1d4 psychic damage."
    },
    moderate: {
        1: "You are the center of a moderate explosion. You and each creature within 30 feet of you must make a Dexterity saving throw against your spell save DC, taking 2d10 force damage for each level of your character on a failed save, or half as much damage on a successful one.",
        2: "You recover half of all expended class resources.",
        3: "You are deafened for 1 day.",
        4: "You are silenced for 1 day.",
        5: "You are poisoned for 1 day.",
        6: "You are invisible for 1 day.",
        7: "Each creature within 30 feet of you takes 2d6 necrotic damage. You regain hit points equal to the sum of damage dealt.",
        8: "You are teleported to an empty demiplane for 1 minute before returning to the location you left.",
        9: "You are protected from creatures from the same plane as the one you're currently on for 1 hour. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC  and will focus on other targets if they can.",
        10: "You are at the center of a darkness spell for 1 day.",
        11: "You are frightened by the nearest creature for 1 minute.",
        12: "You are resistant to all damage types for 1 minute.",
        13: "All other creatures within 60 feet of you become poisoned for 1 minute.",
        14: "All other creatures within 60 feet of you become blinded for 1 minute.",
        15: "All other creatures within 60 feet of you become deafened for 1 minute.",
        16: "All other creatures within 60 feet of you become invisible for 1 minute.",
        17: "All other creatures within 60 feet of you become restrained for 1 minute.",
        18: "You immediately gain 3d20 temporary hit points.",
        19: "You immediately lose any temporary hit points you have and drop to 1d20 hp.",
        20: "All attack rolls against you are made with advantage for 1 day.",
        21: "All attack rolls against you are made with disadvantage for 1 day.",
        22: "For 1 minute, other creatures have advantage on saving throws against spells you cast.",
        23: "For 1 minute, other creatures have disadvantage on saving throws against spells you cast.",
        24: "A demon whose CR is equal to 3/4 of your level appears near you. Make a Charisma saving throw against your own spell save DC. If you make it, the demon is subservient, otherwise, it is hostile. The demon, if not banished or defeated, vanishes after 1 day.",
        25: "All other creatures within 30ft regain 2d8 hit points each. Then you take necrotic damage for the sum of all hit points restored this way.",
        26: "For 1 month, your size is reduced by 1 category.",
        27: "For 1 month, your size is reduced by 1 category.",
        28: "For 1 month, your size is increased by 1 category.",
        29: "You transform into a medium-sized potted plant for 1 minute, during which time you are considered petrified.",
        30: "1d20 random gems appear near you, worth 500gp each.",
        31: "All creatures within 30ft are knocked prone.",
        32: "Whenever you make an ability check using Strength, subtract 1d4 from the result. This effect is permanent.",
        33: "Whenever you make an ability check using Dexterity, subtract 1d4 from the result. This effect is permanent.",
        34: "Whenever you make an ability check using Constitution, subtract 1d4 from the result. This effect is permanent.",
        35: "Whenever you make an ability check using Intelligence, subtract 1d4 from the result. This effect is permanent.",
        36: "Whenever you make an ability check using Wisdom, subtract 1d4 from the result. This effect is permanent.",
        37: "Whenever you make an ability check using Charisma, subtract 1d4 from the result. This effect is permanent.",
        38: "Whenever you make an ability check using Strength, add 1d4 to the result. This effect is permanent.",
        39: "Whenever you make an ability check using Dexterity, add 1d4 to the result. This effect is permanent.",
        40: "Whenever you make an ability check using Constitution, add 1d4 to the result. This effect is permanent.",
        41: "Whenever you make an ability check using Intelligence, add 1d4 to the result. This effect is permanent.",
        42: "Whenever you make an ability check using Wisdom, add 1d4 to the result. This effect is permanent.",
        43: "Whenever you make an ability check using Charisma, add 1d4 to the result. This effect is permanent.",
        44: "For 1 week, no creature within 30ft of you can cast spells of 3th level or lower.",
        45: "During this turn, you can take move and take actions equivalent to taking 3 turns.",
        46: "Your maximum hit points are permanently increased by 2d10.",
        47: "Your lowest ability score is permanently increased by 2.",
        48: "Your highest ability score is permanently reduced by 2.",
        49: "For 1 minute, you can cast any spell with a casting time of 1 action as a bonus action and you can take the attack as a bonus action.",
        50: "You immediately cause 2d4 additional wild magic surges.",
        51: "For 1 hour min, ranged attacks or spells with a range of more than touch, have a range of melee or touch instead.",
        52: "All creatures within 30 feet must make a Wisdom saving throw against your spell save DC. Any creature immune to magical sleep automatically succeeds on its saving throw. Those that fail fall asleep for 1 minute.",
        53: "For 1 minute, every time you hit a creature with an attack, it is pulled 10ft towards you.",
        54: "For 1 minute, every time you hit a creature with an attack, it is pushed 10ft away from you.",
        55: "You jump forward in time exactly 30 seconds. From the perspective of everyone else, you simply cease to exist during that time.",
        56: "For 1 minute, each player looses control over their character and instead gains control over the character who's session inspiration they can see. After the effect ends, the characters themselves don't understand what happened.",
        57: "Your walking speed is permanently increased by 20ft.",
        58: "Your walking speed is permanently decreased by 20ft.",
        59: "Whenever a creature talks to you for the first time during the effect's duration, you flip a coin. If it lands on heads, you punch them in the face, otherwise you hug them. You are not aware of this effect being anything other than you openly expressing your feelings. The effect lasts for 1 day.",
        60: "For 1 hour, your vocabulary is limited to the words \"Yes\" and \"No\", which you can only scream. During this time you cannot cast spells with verbal components.",
        61: "While asleep, you snore so loudly that no other creature within 1000ft can sleep.",
        62: "You and everything you're wearing and carrying are instantly, and without warning, transported to (1d3: 1=the astral plane, 2=the etherial plane, 3=your childhood home). Your companions know exactly where you are.",
        63: "For 1 hour, you cannot willingly move further than away 30ft from your current location. If you are moved outside this range, you must take any and all actions you can to get back as quickly as possible. Behaving like this seems perfectly reasonable to you.",
        64: "For 1 day, you can only move via jumping, and you cannot choose to jump less than the maximum distance you're able to jump.",
        65: "For 1 hour, you can speak with animals but trying to speak any language will result in you making random animal noises.",
        66: "You take 1 damage for every 100gp worth of currency you're carrying.",
        67: "You gain the ability to breathe water but loose the ability to breathe air for 1 hour.",
        68: "For 1 hour, everything you say will also be written in the sky as per the Skywrite spell.",
        69: "For 1 hour, you can pass through any solid, non-magical wall that is 6 or fewer inches thick.",
        70: "Whenever you take a long rest, a severed head appears in your bed. The head belongs to a humanoid creature that was recently murdered.",
        71: "For 1 week, every time you walk through a door or gate it will slam shut behind you and refuse to let anyone except you through.",
        72: "For 1 minute, you are unable to cast any spell that causes damage of any type.",
        73: "You immediately lose all unspent class resources and may not regain them until you have finished a long rest.",
        74: "All your clothing and equipment teleports to the nearest unoccupied space at least 60 feet from you that you can see.",
        75: "For 1 week, you can only speak while music is playing.",
        76: "For 1 week, you are surrounded by faint, ethereal music.",
        77: "Your hair permanently changes color. (1d8: 1=Red, 2=Green, 3=Blue, 4= Purple, 5= Yellow, 6=Grey, 7=White, 8=Black)",
        78: "For 1 hour, all spells  with a casting time of 1 action or 1 bonus action require 2 consecutive actions to cast.",
        79: "For one day, while you're speaking you gain the effect of the Light spell.",
        80: "All beverages within 30ft of you transform into lukewarm water when drunk.",
        81: "For 1 week, every time you say a word that begins with an 's', it sounds like you're hissing like a snake.",
        82: "Some god has taken issue with the last thing you said or did. You immediately take 5d10 radiant damage.",
        83: "Approximately 1000 gallons of water appear over your head and those within 100 feet of you, evenly distributed above everybody within the radius.",
        84: "For week day, you are unable to read as the letters all appeared jumbled.",
        85: "For the next hour, everything you say must rhyme. If it doesn't, you take 1d4 psychic damage."
    },
    minor: {
        1: "You are the center of a small explosion. You and each creature within 10 feet of you must make a Dexterity saving throw against your spell save DC, taking 2d8 force damage for each level of your character on a failed save, or half as much damage on a successful one.",
        2: "You recover a single expended class resource.",
        3: "You are deafened for 1 hour.",
        4: "You are silenced for 1 hour.",
        5: "You are poisoned for 1 hour.",
        6: "You are invisible for 1 hour.",
        7: "Each creature within 10 feet of you takes 2d4 necrotic damage. You regain hit points equal to the sum of damage dealt.",
        8: "You are teleported to an empty demiplane for 1 round before returning to the location you left.",
        9: "You are protected from creatures from the same plane as the one you're currently on for 1 minute. Such creatures cannot attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC  and will focus on other targets if they can.",
        10: "You are at the center of a darkness spell for 1 hour.",
        11: "You are frightened by the nearest creature for 1 round.",
        12: "You are resistant to all damage types for 1 round.",
        13: "All other creatures within 60 feet of you become poisoned for 1 round.",
        14: "All other creatures within 60 feet of you become blinded for 1 round.",
        15: "All other creatures within 60 feet of you become deafened for 1 round.",
        16: "All other creatures within 60 feet of you become invisible for 1 round.",
        17: "All other creatures within 60 feet of you become restrained for 1 round.",
        18: "You immediately gain 3d12 temporary hit points.",
        19: "You immediately lose any temporary hit points you have and drop to 1d100 hp.",
        20: "All attack rolls against you are made with advantage for 1 hour.",
        21: "All attack rolls against you are made with disadvantage for 1 hour.",
        22: "For 1 round, other creatures have advantage on saving throws against spells you cast.",
        23: "For 1 round, other creatures have disadvantage on saving throws against spells you cast.",
        24: "A demon whose CR is equal to 1/2 of your level appears near you. Make a Charisma saving throw against your own spell save DC. If you make it, the demon is subservient, otherwise, it is hostile. The demon, if not banished or defeated, vanishes after 1 day.",
        25: "All other creatures within 10ft regain 2d8 hit points each. Then you take necrotic damage for the sum of all hit points restored this way.",
        26: "For 1 week, your size is reduced by 1 category.",
        27: "For 1 week, your size is increased by 1 category.",
        28: "You transform into a medium-sized potted plant for 1 round, during which time you are considered petrified.",
        29: "1d20 random gems appear near you, worth 50gp each.",
        30: "All creatures within 10ft are knocked prone.",
        31: "Whenever you make an ability check using Strength, subtract 1 from the result. This effect is permanent.",
        32: "Whenever you make an ability check using Dexterity, subtract 1 from the result. This effect is permanent.",
        33: "Whenever you make an ability check using Constitution, subtract 1 from the result. This effect is permanent.",
        34: "Whenever you make an ability check using Intelligence, subtract 1 from the result. This effect is permanent.",
        35: "Whenever you make an ability check using Wisdom, subtract 1 from the result. This effect is permanent.",
        36: "Whenever you make an ability check using Charisma, subtract 1 from the result. This effect is permanent.",
        37: "Whenever you make an ability check using Strength, add 1 to the result. This effect is permanent.",
        38: "Whenever you make an ability check using Dexterity, add 1 to the result. This effect is permanent.",
        39: "Whenever you make an ability check using Constitution, add 1 to the result. This effect is permanent.",
        40: "Whenever you make an ability check using Intelligence, add 1 to the result. This effect is permanent.",
        41: "Whenever you make an ability check using Wisdom, add 1 to the result. This effect is permanent.",
        42: "Whenever you make an ability check using Charisma, add 1 to the result. This effect is permanent.",
        43: "For 1 week, no creature within 10ft of you can cast spells of 1st level or lower.",
        44: "During this turn, you can take move and take actions equivalent to taking 2 turns.",
        45: "Your maximum hit points are permanently increased by 1d10.",
        46: "Your lowest ability score is permanently increased by 1.",
        47: "Your highest ability score is permanently reduced by 1.",
        48: "For 1 round, you can cast any spell with a casting time of 1 action as a bonus action and you can take the attack as a bonus action.",
        49: "You immediately cause 2 additional wild magic surges.",
        50: "For 1 minute min, ranged attacks or spells with a range of more than touch, have a range of melee or touch instead.",
        51: "All creatures within 60 feet must make a Wisdom saving throw against your spell save DC. Any creature immune to magical sleep automatically succeeds on its saving throw. Those that fail fall asleep for 1 round.",
        52: "For 1 round, every time you hit a creature with an attack, it is pulled 10ft towards you.",
        53: "For 1 round, every time you hit a creature with an attack, it is pushed 10ft away from you.",
        54: "You jump forward in time exactly 6 seconds. From the perspective of everyone else, you simply cease to exist during that time.",
        55: "For 1 round, each player looses control over their character and instead gains control over the character who's session inspiration they can see. After the effect ends, the characters themselves don't understand what happened.",
        56: "Your walking speed is permanently increased by 10ft.",
        57: "Your walking speed is permanently decreased by 10ft.",
        58: "Whenever a creature talks to you for the first time during the effect's duration, you flip a coin. If it lands on heads, you punch them in the face, otherwise you hug them. You are not aware of this effect being anything other than you openly expressing your feelings. The effect lasts for 1 hour.",
        59: "For 1 minute, your vocabulary is limited to the words \"Yes\" and \"No\", which you can only scream. During this time you cannot cast spells with verbal components.",
        60: "While asleep, you snore so loudly that no other creature within 100ft can sleep.",
        61: "You and everything you're wearing and carrying are instantly, and without warning, transported to the place where you last took a long rest. Your companions know exactly where you are.",
        62: "For 1 minute, you cannot willingly move further than away 30ft from your current location. If you are moved outside this range, you must take any and all actions you can to get back as quickly as possible. Behaving like this seems perfectly reasonable to you.",
        63: "For 1 hour, you can only move via jumping, and you cannot choose to jump less than the maximum distance you're able to jump.",
        64: "For 1 minute, you can speak with animals but trying to speak any language will result in you making random animal noises.",
        65: "You take 1 damage for every 1000gp worth of currency you're carrying.",
        66: "You gain the ability to breathe water but loose the ability to breathe air for 1 minute.",
        67: "For 1 minute, everything you say will also be written in the sky as per the Skywrite spell.",
        68: "For 1 minute, you can pass through any solid, non-magical wall that is 6 or fewer inches thick.",
        69: "Whenever you take a long rest, a severed hand appears in your bed. The hand belongs to a humanoid creature that was recently murdered.",
        70: "For 1 day, every time you walk through a door or gate it will slam shut behind you and refuse to let anyone except you through.",
        71: "For 1 round, you are unable to cast any spell that causes damage of any type.",
        72: "All your clothing and equipment teleports to the nearest unoccupied space at least 30 feet from you that you can see.",
        73: "For 1 day, you can only speak while music is playing.",
        74: "For 1 day, you are surrounded by faint, ethereal music.",
        75: "Your eyes permanently change color. (1d8: 1=Red, 2=Green, 3=Blue, 4= Purple, 5= Yellow, 6=Grey, 7=White, 8=Black)",
        76: "For 1 minute, all spells  with a casting time of 1 action or 1 bonus action require 2 consecutive actions to cast.",
        77: "For 1 minute, while you're speaking you gain the effect of the Light spell.",
        78: "All beverages within 10ft of you transform into lukewarm water when drunk.",
        79: "For 1 day, every time you say a word that begins with an 's', it sounds like you're hissing like a snake.",
        80: "Some god has taken issue with the last thing you said or did. You immediately take 1d8 radiant damage.",
        81: "Approximately 100 gallons of water appear over your head and those within 10 feet of you, evenly distributed above everybody within the radius.",
        82: "You permanently gain the ability to talk to nonexistent things.",
        83: "For 1 day, you are unable to read as the letters all appeared jumbled.",
        84: "For the next minute, everything you say must rhyme. If it doesn't, you take 1d4 psychic damage."
    }
};
